### ISSUE TITLE
大佬好，可以在vps上部署吗

### ISSUE THREAD

**Issue by beautygirl1998** [14790897/full-forward-proxy#6]
谢谢这么好的工具。请问可以在vps上部署吗？vps服务器访问要快一些。

**Comment by 14790897** [comment]
不能，我没实现

**Comment by 14790897** [comment]
你是beautiful girl吗？

**Comment by 14790897** [comment]
难道是男娘？

**Comment by 14790897** [comment]
一般人不会说自己很漂亮吧

**Comment by JuneLee2024** [comment]
我做出来只能维持19秒钟，就出现“出了点问题。请刷新或稍后重试。[了解详情](https://support.google.com/youtube?p=videoError&hl=zh-CN)”
最好能出VPS版。
另外，我是漂亮的女孩。

**Comment by 14790897** [comment]
> 我做出来只能维持19秒钟，就出现“出了点问题。请刷新或稍后重试。[了解详情](https://support.google.com/youtube?p=videoError&hl=zh-CN)” 最好能出VPS版。 另外，我是漂亮的女孩。

正常人怎么会说自己是漂亮女孩呢，再说了，你是漂亮女孩难道能和我做爱吗？

**Comment by JuneLee2024** [comment]
我应该不是正常人吧。
但主题不是这玩意儿不行吗？
